import { Kanit } from "next/font/google"; // ✅ Import Kanit
import "./globals.css";
import Providers from "@/lib/povider";
import Nav from "@/componets/nav";
import Footer from "@/componets/footer";

const kanit = Kanit({
  variable: "--font-kanit",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // optional: include required weights
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${kanit.variable} antialiased`}>
        <Providers>
          <Nav />
          {children}
        </Providers>
        <Footer />
      </body>
    </html>
  );
}
